/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.cjoakim.cosmos;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("42 is just silly", "42");
    }
}
